version: '3'
services:
  libremdb:
    container_name: libremdb
    image: quay.io/pussthecatorg/libremdb:latest
    restart: unless-stopped
    networks:
      - nginx
    environment:
      - "PORT=8809"
      - "URL=http://localhost:8809"
      - "NODE_ENV=production"
      - "IMAGE_QUALITY=500"

networks:
  nginx:
    external: true
