version: '3'
services:
  proxitok:
    container_name: proxitok
    image: ghcr.io/pablouser1/proxitok:master
    # ports:
    #   - 8807:80
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok_redis
      - REDIS_PORT=6379
      - API_SIGNER=remote
      - API_SIGNER_URL=http://proxitok_signer:8080/signature
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - proxitok_redis
      - proxitok_signer
    networks:
      - nginx
      - proxitok
    restart: unless-stopped

  proxitok_redis:
    container_name: proxitok_redis
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - proxitok

  proxitok_signer:
    container_name: proxitok_signer
    image: ghcr.io/pablouser1/signtok:master
    restart: unless-stopped
    networks:
      - proxitok

volumes:
  proxitok-cache:

networks:
  nginx:
    external: true
  proxitok:
